# version: "3.9"

# services:
#   react-app:
#     image: fivegunners/yekikame-react:latest # Replace with your Docker image
#     container_name: react-app
#     ports:
#       - "8080:80" # Maps port 80 on the host to port 80 in the container
#     restart: unless-stopped
version: '3.8'

services:
  react-frontend:
    build:
      context: .  # Directory containing Dockerfile, source code, and nginx.conf
      dockerfile: Dockerfile
    image: react-nginx:latest  # Name for the built image
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
    restart: always