name: React CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: npm run build

    - name: Deploy to VPS via SCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_DEPLOY_PATH: ${{ secrets.VPS_DEPLOY_PATH }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOST "sudo apt-get update && sudo apt-get install -y nodejs npm nginx"
        scp -r ./dist $VPS_USERNAME@$VPS_HOST:$VPS_DEPLOY_PATH

    - name: Restart Nginx on VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOST "sudo systemctl restart nginx"
