name: React CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Build React app
    - name: Build React app
      run: npm run build

    # Step 5: Configure SSH and Debug Key Setup
    - name: Configure SSH and Debug Key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "=== First few lines of the private key ==="
        head -n 5 ~/.ssh/id_rsa
        echo "=== End of debug ==="
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 6: Debug SSH Connection
    - name: Test SSH Connection
      run: |
        ssh -v -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOST "echo 'SSH connection successful'"
      env:
        VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        VPS_HOST: ${{ secrets.VPS_HOST }}

    # Step 7: Deploy files to VPS
    - name: Deploy React App to VPS
      env:
        VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_DEPLOY_PATH: ${{ secrets.VPS_DEPLOY_PATH }}
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOST "mkdir -p $VPS_DEPLOY_PATH"
        scp -r ./dist $VPS_USERNAME@$VPS_HOST:$VPS_DEPLOY_PATH

    # Step 8: Reload Nginx
    - name: Reload Nginx on VPS
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOST "
          sudo nginx -t && sudo systemctl reload nginx
        "
      env:
        VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        VPS_HOST: ${{ secrets.VPS_HOST }}

